version: '3'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
     - "8081:80"
    volumes:
      - ./www:/var/www/html
    environment:
        XDEBUG_CONFIG: remote_host=127.0.0.1
networks:
  default:
    external:
      name: webapps